[default]
parameters = [
    "-noSplash",
    "-skipIntro",
    "-showScriptErrors",
]

[vr]
extends = "default"
parameters = [
    "-init=playMission['','\\x\\aware\\addons\\main\\missions\\HelloWorld.VR']",
]

[eden]
extends = "default"
mission = "addons/main/missions/HelloWorld.VR"
